/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { DemandeAutreCharge } from "./DemandeAutreCharge";
import { DemandeAutreChargeCountArgs } from "./DemandeAutreChargeCountArgs";
import { DemandeAutreChargeFindManyArgs } from "./DemandeAutreChargeFindManyArgs";
import { DemandeAutreChargeFindUniqueArgs } from "./DemandeAutreChargeFindUniqueArgs";
import { CreateDemandeAutreChargeArgs } from "./CreateDemandeAutreChargeArgs";
import { UpdateDemandeAutreChargeArgs } from "./UpdateDemandeAutreChargeArgs";
import { DeleteDemandeAutreChargeArgs } from "./DeleteDemandeAutreChargeArgs";
import { Demande } from "../../demande/base/Demande";
import { DemandeAutreChargeService } from "../demandeAutreCharge.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DemandeAutreCharge)
export class DemandeAutreChargeResolverBase {
  constructor(
    protected readonly service: DemandeAutreChargeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DemandeAutreCharge",
    action: "read",
    possession: "any",
  })
  async _demandeAutreChargesMeta(
    @graphql.Args() args: DemandeAutreChargeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DemandeAutreCharge])
  @nestAccessControl.UseRoles({
    resource: "DemandeAutreCharge",
    action: "read",
    possession: "any",
  })
  async demandeAutreCharges(
    @graphql.Args() args: DemandeAutreChargeFindManyArgs
  ): Promise<DemandeAutreCharge[]> {
    return this.service.demandeAutreCharges(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DemandeAutreCharge, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DemandeAutreCharge",
    action: "read",
    possession: "own",
  })
  async demandeAutreCharge(
    @graphql.Args() args: DemandeAutreChargeFindUniqueArgs
  ): Promise<DemandeAutreCharge | null> {
    const result = await this.service.demandeAutreCharge(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DemandeAutreCharge)
  @nestAccessControl.UseRoles({
    resource: "DemandeAutreCharge",
    action: "create",
    possession: "any",
  })
  async createDemandeAutreCharge(
    @graphql.Args() args: CreateDemandeAutreChargeArgs
  ): Promise<DemandeAutreCharge> {
    return await this.service.createDemandeAutreCharge({
      ...args,
      data: {
        ...args.data,

        demande: {
          connect: args.data.demande,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DemandeAutreCharge)
  @nestAccessControl.UseRoles({
    resource: "DemandeAutreCharge",
    action: "update",
    possession: "any",
  })
  async updateDemandeAutreCharge(
    @graphql.Args() args: UpdateDemandeAutreChargeArgs
  ): Promise<DemandeAutreCharge | null> {
    try {
      return await this.service.updateDemandeAutreCharge({
        ...args,
        data: {
          ...args.data,

          demande: {
            connect: args.data.demande,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DemandeAutreCharge)
  @nestAccessControl.UseRoles({
    resource: "DemandeAutreCharge",
    action: "delete",
    possession: "any",
  })
  async deleteDemandeAutreCharge(
    @graphql.Args() args: DeleteDemandeAutreChargeArgs
  ): Promise<DemandeAutreCharge | null> {
    try {
      return await this.service.deleteDemandeAutreCharge(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Demande, {
    nullable: true,
    name: "demande",
  })
  @nestAccessControl.UseRoles({
    resource: "Demande",
    action: "read",
    possession: "any",
  })
  async getDemande(
    @graphql.Parent() parent: DemandeAutreCharge
  ): Promise<Demande | null> {
    const result = await this.service.getDemande(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
