/*
------------------------------------------------------------------------------
This code was generated by Amplication.

Changes to this file will be lost if the code is regenerated.

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DemandeAutreChargeService } from "../demandeAutreCharge.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DemandeAutreChargeCreateInput } from "./DemandeAutreChargeCreateInput";
import { DemandeAutreCharge } from "./DemandeAutreCharge";
import { DemandeAutreChargeFindManyArgs } from "./DemandeAutreChargeFindManyArgs";
import { DemandeAutreChargeWhereUniqueInput } from "./DemandeAutreChargeWhereUniqueInput";
import { DemandeAutreChargeUpdateInput } from "./DemandeAutreChargeUpdateInput";

const SELECT = {
  createdAt: true,
  demande: {
    select: {
      id: true,
    },
  },
  id: true,
  nom: true,
  montant: true,
  updatedAt: true,
} as const;

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DemandeAutreChargeControllerBase {
  constructor(
    protected readonly service: DemandeAutreChargeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DemandeAutreCharge })
  @nestAccessControl.UseRoles({
    resource: "DemandeAutreCharge",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDemandeAutreCharge(
    @common.Body() data: DemandeAutreChargeCreateInput
  ): Promise<DemandeAutreCharge> {
    return await this.service.createDemandeAutreCharge({
      data: {
        ...data,

        demande: {
          connect: data.demande,
        },
      },
      select: SELECT,
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DemandeAutreCharge] })
  @ApiNestedQuery(DemandeAutreChargeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DemandeAutreCharge",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async demandeAutreCharges(
    @common.Req() request: Request
  ): Promise<DemandeAutreCharge[]> {
    const args = plainToClass(DemandeAutreChargeFindManyArgs, request.query);
    return this.service.demandeAutreCharges({
      ...args,
      select: SELECT,
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DemandeAutreCharge })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DemandeAutreCharge",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async demandeAutreCharge(
    @common.Param() params: DemandeAutreChargeWhereUniqueInput
  ): Promise<DemandeAutreCharge | null> {
    const result = await this.service.demandeAutreCharge({
      where: params,
      select: SELECT,
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DemandeAutreCharge })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DemandeAutreCharge",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDemandeAutreCharge(
    @common.Param() params: DemandeAutreChargeWhereUniqueInput,
    @common.Body() data: DemandeAutreChargeUpdateInput
  ): Promise<DemandeAutreCharge | null> {
    try {
      return await this.service.updateDemandeAutreCharge({
        where: params,
        data: {
          ...data,

          demande: {
            connect: data.demande,
          },
        },
        select: SELECT,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DemandeAutreCharge })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DemandeAutreCharge",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDemandeAutreCharge(
    @common.Param() params: DemandeAutreChargeWhereUniqueInput
  ): Promise<DemandeAutreCharge | null> {
    try {
      return await this.service.deleteDemandeAutreCharge({
        where: params,
        select: SELECT,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
