/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AideWhereUniqueInput } from "../../aide/base/AideWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ContactWhereUniqueInput } from "../../contact/base/ContactWhereUniqueInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { DemandeWhereUniqueInput } from "../../demande/base/DemandeWhereUniqueInput";
import { TypeDocumentWhereUniqueInput } from "../../typeDocument/base/TypeDocumentWhereUniqueInput";
import { VersementWhereUniqueInput } from "../../versement/base/VersementWhereUniqueInput";
import { VisiteWhereUniqueInput } from "../../visite/base/VisiteWhereUniqueInput";

@InputType()
class DocumentCreateInput {
  @ApiProperty({
    required: false,
    type: () => AideWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AideWhereUniqueInput)
  @IsOptional()
  @Field(() => AideWhereUniqueInput, {
    nullable: true,
  })
  aide?: AideWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ContactWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ContactWhereUniqueInput)
  @IsOptional()
  @Field(() => ContactWhereUniqueInput, {
    nullable: true,
  })
  contact?: ContactWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  contenu?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => DemandeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DemandeWhereUniqueInput)
  @IsOptional()
  @Field(() => DemandeWhereUniqueInput, {
    nullable: true,
  })
  demande?: DemandeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => TypeDocumentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TypeDocumentWhereUniqueInput)
  @IsOptional()
  @Field(() => TypeDocumentWhereUniqueInput, {
    nullable: true,
  })
  typeDocument?: TypeDocumentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => VersementWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => VersementWhereUniqueInput)
  @IsOptional()
  @Field(() => VersementWhereUniqueInput, {
    nullable: true,
  })
  versements?: VersementWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => VisiteWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => VisiteWhereUniqueInput)
  @IsOptional()
  @Field(() => VisiteWhereUniqueInput, {
    nullable: true,
  })
  visites?: VisiteWhereUniqueInput | null;
}

export { DocumentCreateInput as DocumentCreateInput };
