/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Contact } from "../../contact/base/Contact";

import {
  ValidateNested,
  IsDate,
  IsEnum,
  IsOptional,
  IsInt,
  IsString,
  MaxLength,
  Max,
  IsBoolean,
} from "class-validator";

import { Type } from "class-transformer";
import { EnumAideCrediteur } from "./EnumAideCrediteur";
import { Demande } from "../../demande/base/Demande";
import { DemandeActivity } from "../../demandeActivity/base/DemandeActivity";
import { Document } from "../../document/base/Document";
import { EnumAideFrequence } from "./EnumAideFrequence";
import { EnumAideStatus } from "./EnumAideStatus";
import { EnumAideTypeField } from "./EnumAideTypeField";
import { Versement } from "../../versement/base/Versement";

@ObjectType()
class Aide {
  @ApiProperty({
    required: true,
    type: () => Contact,
  })
  @ValidateNested()
  @Type(() => Contact)
  contact?: Contact;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    enum: EnumAideCrediteur,
  })
  @IsEnum(EnumAideCrediteur)
  @IsOptional()
  @Field(() => EnumAideCrediteur, {
    nullable: true,
  })
  crediteur?: "LeBNFiciaire" | "UnCrAncier" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateAide!: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateExpiration!: Date | null;

  @ApiProperty({
    required: false,
    type: () => Demande,
  })
  @ValidateNested()
  @Type(() => Demande)
  @IsOptional()
  demande?: Demande | null;

  @ApiProperty({
    required: false,
    type: () => [DemandeActivity],
  })
  @ValidateNested()
  @Type(() => DemandeActivity)
  @IsOptional()
  demandeActivities?: Array<DemandeActivity>;

  @ApiProperty({
    required: false,
    type: () => [Document],
  })
  @ValidateNested()
  @Type(() => Document)
  @IsOptional()
  documents?: Array<Document>;

  @ApiProperty({
    required: false,
    enum: EnumAideFrequence,
  })
  @IsEnum(EnumAideFrequence)
  @IsOptional()
  @Field(() => EnumAideFrequence, {
    nullable: true,
  })
  frequence?:
    | "Mensuelle"
    | "BiMensuelle"
    | "Trimestrielle"
    | "Hebdomadaire"
    | "Unefois"
    | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  id!: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  infosCrediteur!: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  montant!: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  nombreVersements!: number | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  reetudier!: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(10000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  remarque!: string | null;

  @ApiProperty({
    required: true,
    enum: EnumAideStatus,
  })
  @IsEnum(EnumAideStatus)
  @Field(() => EnumAideStatus, {
    nullable: true,
  })
  status?: "EnCours" | "Expir";

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  suspendue!: boolean | null;

  @ApiProperty({
    required: false,
    enum: EnumAideTypeField,
  })
  @IsEnum(EnumAideTypeField)
  @IsOptional()
  @Field(() => EnumAideTypeField, {
    nullable: true,
  })
  typeField?: "AssistanceAdministrative" | "FinanciRe" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [Versement],
  })
  @ValidateNested()
  @Type(() => Versement)
  @IsOptional()
  versements?: Array<Versement>;
}

export { Aide as Aide };
