version: "3"
services:
   redis_broker:
    container_name: ${REDIS_BROKER_HOST}
    image: redis:7
    ports:
      - ${REDIS_BROKER_PORT}:6379
    volumes:
      - redis_broker:/redis-broker-data
volumes:
  redis_broker:
    driver: local
