/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DemandeSituationHistoryService } from "../demandeSituationHistory.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DemandeSituationHistoryCreateInput } from "./DemandeSituationHistoryCreateInput";
import { DemandeSituationHistory } from "./DemandeSituationHistory";
import { DemandeSituationHistoryFindManyArgs } from "./DemandeSituationHistoryFindManyArgs";
import { DemandeSituationHistoryWhereUniqueInput } from "./DemandeSituationHistoryWhereUniqueInput";
import { DemandeSituationHistoryUpdateInput } from "./DemandeSituationHistoryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DemandeSituationHistoryControllerBase {
  constructor(
    protected readonly service: DemandeSituationHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DemandeSituationHistory })
  @nestAccessControl.UseRoles({
    resource: "DemandeSituationHistory",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDemandeSituationHistory(
    @common.Body() data: DemandeSituationHistoryCreateInput
  ): Promise<DemandeSituationHistory> {
    return await this.service.createDemandeSituationHistory({
      data: {
        ...data,

        demande: {
          connect: data.demande,
        },

        creePar: data.creePar
          ? {
              connect: data.creePar,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        demande: {
          select: {
            id: true,
          },
        },

        creePar: {
          select: {
            id: true,
          },
        },

        id: true,
        nombreEnfants: true,
        nombrePersonnes: true,
        agesEnfants: true,
        situationFamiliale: true,
        situationProfessionnelle: true,
        situationProConjoint: true,
        revenus: true,
        revenusConjoint: true,
        loyer: true,
        facturesEnergie: true,
        dettes: true,
        natureDettes: true,
        autresAides: true,
        autresCharges: true,
        apl: true,
        categorieDemandeur: true,
        remarques: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DemandeSituationHistory] })
  @ApiNestedQuery(DemandeSituationHistoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DemandeSituationHistory",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async demandeSituationHistories(
    @common.Req() request: Request
  ): Promise<DemandeSituationHistory[]> {
    const args = plainToClass(DemandeSituationHistoryFindManyArgs, request.query);
    return this.service.demandeSituationHistories({
      ...args,
      select: {
        createdAt: true,

        demande: {
          select: {
            id: true,
          },
        },

        creePar: {
          select: {
            id: true,
          },
        },

        id: true,
        nombreEnfants: true,
        nombrePersonnes: true,
        agesEnfants: true,
        situationFamiliale: true,
        situationProfessionnelle: true,
        situationProConjoint: true,
        revenus: true,
        revenusConjoint: true,
        loyer: true,
        facturesEnergie: true,
        dettes: true,
        natureDettes: true,
        autresAides: true,
        autresCharges: true,
        apl: true,
        categorieDemandeur: true,
        remarques: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DemandeSituationHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DemandeSituationHistory",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async demandeSituationHistory(
    @common.Param() params: DemandeSituationHistoryWhereUniqueInput
  ): Promise<DemandeSituationHistory | null> {
    const result = await this.service.demandeSituationHistory({
      where: params,
      select: {
        createdAt: true,

        demande: {
          select: {
            id: true,
          },
        },

        creePar: {
          select: {
            id: true,
          },
        },

        id: true,
        nombreEnfants: true,
        nombrePersonnes: true,
        agesEnfants: true,
        situationFamiliale: true,
        situationProfessionnelle: true,
        situationProConjoint: true,
        revenus: true,
        revenusConjoint: true,
        loyer: true,
        facturesEnergie: true,
        dettes: true,
        natureDettes: true,
        autresAides: true,
        autresCharges: true,
        apl: true,
        categorieDemandeur: true,
        remarques: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DemandeSituationHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DemandeSituationHistory",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDemandeSituationHistory(
    @common.Param() params: DemandeSituationHistoryWhereUniqueInput,
    @common.Body() data: DemandeSituationHistoryUpdateInput
  ): Promise<DemandeSituationHistory | null> {
    try {
      return await this.service.updateDemandeSituationHistory({
        where: params,
        data: {
          ...data,

          demande: {
            connect: data.demande,
          },

          creePar: data.creePar
            ? {
                connect: data.creePar,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          demande: {
            select: {
              id: true,
            },
          },

          creePar: {
            select: {
              id: true,
            },
          },

          id: true,
          nombreEnfants: true,
          nombrePersonnes: true,
          agesEnfants: true,
          situationFamiliale: true,
          situationProfessionnelle: true,
          situationProConjoint: true,
          revenus: true,
          revenusConjoint: true,
          loyer: true,
          facturesEnergie: true,
          dettes: true,
          natureDettes: true,
          autresAides: true,
          autresCharges: true,
          apl: true,
          categorieDemandeur: true,
          remarques: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DemandeSituationHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DemandeSituationHistory",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDemandeSituationHistory(
    @common.Param() params: DemandeSituationHistoryWhereUniqueInput
  ): Promise<DemandeSituationHistory | null> {
    try {
      return await this.service.deleteDemandeSituationHistory({
        where: params,
        select: {
          createdAt: true,

          demande: {
            select: {
              id: true,
            },
          },

          creePar: {
            select: {
              id: true,
            },
          },

          id: true,
          nombreEnfants: true,
          nombrePersonnes: true,
          agesEnfants: true,
          situationFamiliale: true,
          situationProfessionnelle: true,
          situationProConjoint: true,
          revenus: true,
          revenusConjoint: true,
          loyer: true,
          facturesEnergie: true,
          dettes: true,
          natureDettes: true,
          autresAides: true,
          autresCharges: true,
          apl: true,
          categorieDemandeur: true,
          remarques: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
