/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WebsiteDemandeService } from "../websiteDemande.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WebsiteDemandeCreateInput } from "./WebsiteDemandeCreateInput";
import { WebsiteDemande } from "./WebsiteDemande";
import { WebsiteDemandeFindManyArgs } from "./WebsiteDemandeFindManyArgs";
import { WebsiteDemandeWhereUniqueInput } from "./WebsiteDemandeWhereUniqueInput";
import { WebsiteDemandeUpdateInput } from "./WebsiteDemandeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WebsiteDemandeControllerBase {
  constructor(
    protected readonly service: WebsiteDemandeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WebsiteDemande })
  @nestAccessControl.UseRoles({
    resource: "WebsiteDemande",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWebsiteDemande(
    @common.Body() data: WebsiteDemandeCreateInput
  ): Promise<WebsiteDemande> {
    return await this.service.createWebsiteDemande({
      data: data,
      select: {
        adresseDemandeur: true,
        ageDemandeur: true,
        agesEnfants: true,
        apl: true,
        autresAides: true,
        autresCharges: true,
        codePostalDemandeur: true,
        createdAt: true,
        dettes: true,
        emailDemandeur: true,
        erreur: true,
        facturesEnergie: true,
        id: true,
        loyer: true,
        natureDettes: true,
        nomDemandeur: true,
        nombreEnfants: true,
        prenomDemandeur: true,
        remarques: true,
        revenus: true,
        revenusConjoint: true,
        contactId:true,
        situationFamiliale: true,
        situationProConjoint: true,
        situationProfessionnelle: true,
        status: true,
        telephoneDemandeur: true,
        updatedAt: true,
        villeDemandeur: true,
        forceNewContact : true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WebsiteDemande] })
  @ApiNestedQuery(WebsiteDemandeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WebsiteDemande",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async websiteDemandes(
    @common.Req() request: Request
  ): Promise<WebsiteDemande[]> {
    const args = plainToClass(WebsiteDemandeFindManyArgs, request.query);
    return this.service.websiteDemandes({
      ...args,
      select: {
        adresseDemandeur: true,
        ageDemandeur: true,
        agesEnfants: true,
        apl: true,
        autresAides: true,
        autresCharges: true,
        codePostalDemandeur: true,
        createdAt: true,
        dettes: true,
        emailDemandeur: true,
        erreur: true,
        facturesEnergie: true,
        id: true,
        loyer: true,
        natureDettes: true,
        nomDemandeur: true,
        nombreEnfants: true,
        prenomDemandeur: true,
        remarques: true,
        revenus: true,
        revenusConjoint: true,
        contactId:true,
        situationFamiliale: true,
        situationProConjoint: true,
        situationProfessionnelle: true,
        status: true,
        telephoneDemandeur: true,
        updatedAt: true,
        villeDemandeur: true,
        forceNewContact : true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WebsiteDemande })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WebsiteDemande",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async websiteDemande(
    @common.Param() params: WebsiteDemandeWhereUniqueInput
  ): Promise<WebsiteDemande | null> {
    const result = await this.service.websiteDemande({
      where: params,
      select: {
        adresseDemandeur: true,
        ageDemandeur: true,
        agesEnfants: true,
        apl: true,
        autresAides: true,
        autresCharges: true,
        codePostalDemandeur: true,
        createdAt: true,
        dettes: true,
        emailDemandeur: true,
        erreur: true,
        facturesEnergie: true,
        id: true,
        loyer: true,
        natureDettes: true,
        nomDemandeur: true,
        nombreEnfants: true,
        prenomDemandeur: true,
        remarques: true,
        revenus: true,
        revenusConjoint: true,
        contactId:true,
        situationFamiliale: true,
        situationProConjoint: true,
        situationProfessionnelle: true,
        status: true,
        telephoneDemandeur: true,
        updatedAt: true,
        villeDemandeur: true,
        forceNewContact : true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WebsiteDemande })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WebsiteDemande",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWebsiteDemande(
    @common.Param() params: WebsiteDemandeWhereUniqueInput,
    @common.Body() data: WebsiteDemandeUpdateInput
  ): Promise<WebsiteDemande | null> {
    try {
      return await this.service.updateWebsiteDemande({
        where: params,
        data: data,
        select: {
          adresseDemandeur: true,
          ageDemandeur: true,
          agesEnfants: true,
          apl: true,
          autresAides: true,
          autresCharges: true,
          codePostalDemandeur: true,
          createdAt: true,
          dettes: true,
          emailDemandeur: true,
          erreur: true,
          facturesEnergie: true,
          id: true,
          loyer: true,
          natureDettes: true,
          nomDemandeur: true,
          nombreEnfants: true,
          prenomDemandeur: true,
          remarques: true,
          revenus: true,
          revenusConjoint: true,
          contactId:true,
          situationFamiliale: true,
          situationProConjoint: true,
          situationProfessionnelle: true,
          status: true,
          telephoneDemandeur: true,
          updatedAt: true,
          villeDemandeur: true,
          forceNewContact : true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WebsiteDemande })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WebsiteDemande",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWebsiteDemande(
    @common.Param() params: WebsiteDemandeWhereUniqueInput
  ): Promise<WebsiteDemande | null> {
    try {
      return await this.service.deleteWebsiteDemande({
        where: params,
        select: {
          adresseDemandeur: true,
          ageDemandeur: true,
          agesEnfants: true,
          apl: true,
          autresAides: true,
          autresCharges: true,
          codePostalDemandeur: true,
          createdAt: true,
          dettes: true,
          emailDemandeur: true,
          erreur: true,
          facturesEnergie: true,
          id: true,
          loyer: true,
          natureDettes: true,
          nomDemandeur: true,
          nombreEnfants: true,
          prenomDemandeur: true,
          remarques: true,
          revenus: true,
          revenusConjoint: true,
          contactId:true,
          situationFamiliale: true,
          situationProConjoint: true,
          situationProfessionnelle: true,
          status: true,
          telephoneDemandeur: true,
          updatedAt: true,
          villeDemandeur: true,
          forceNewContact : true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
