/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DemandeStatusHistoryService } from "../demandeStatusHistory.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DemandeStatusHistoryCreateInput } from "./DemandeStatusHistoryCreateInput";
import { DemandeStatusHistory } from "./DemandeStatusHistory";
import { DemandeStatusHistoryFindManyArgs } from "./DemandeStatusHistoryFindManyArgs";
import { DemandeStatusHistoryWhereUniqueInput } from "./DemandeStatusHistoryWhereUniqueInput";
import { DemandeStatusHistoryUpdateInput } from "./DemandeStatusHistoryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DemandeStatusHistoryControllerBase {
  constructor(
    protected readonly service: DemandeStatusHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DemandeStatusHistory })
  @nestAccessControl.UseRoles({
    resource: "DemandeStatusHistory",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDemandeStatusHistory(
    @common.Body() data: DemandeStatusHistoryCreateInput
  ): Promise<DemandeStatusHistory> {
    return await this.service.createDemandeStatusHistory({
      data: {
        ...data,

        demande: {
          connect: data.demande,
        },
      },
      select: {
        createdAt: true,

        demande: {
          select: {
            id: true,
          },
        },

        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DemandeStatusHistory] })
  @ApiNestedQuery(DemandeStatusHistoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DemandeStatusHistory",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async demandeStatusHistories(
    @common.Req() request: Request
  ): Promise<DemandeStatusHistory[]> {
    const args = plainToClass(DemandeStatusHistoryFindManyArgs, request.query);
    return this.service.demandeStatusHistories({
      ...args,
      select: {
        createdAt: true,

        demande: {
          select: {
            id: true,
          },
        },

        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DemandeStatusHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DemandeStatusHistory",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async demandeStatusHistory(
    @common.Param() params: DemandeStatusHistoryWhereUniqueInput
  ): Promise<DemandeStatusHistory | null> {
    const result = await this.service.demandeStatusHistory({
      where: params,
      select: {
        createdAt: true,

        demande: {
          select: {
            id: true,
          },
        },

        id: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DemandeStatusHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DemandeStatusHistory",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDemandeStatusHistory(
    @common.Param() params: DemandeStatusHistoryWhereUniqueInput,
    @common.Body() data: DemandeStatusHistoryUpdateInput
  ): Promise<DemandeStatusHistory | null> {
    try {
      return await this.service.updateDemandeStatusHistory({
        where: params,
        data: {
          ...data,

          demande: {
            connect: data.demande,
          },
        },
        select: {
          createdAt: true,

          demande: {
            select: {
              id: true,
            },
          },

          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DemandeStatusHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DemandeStatusHistory",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDemandeStatusHistory(
    @common.Param() params: DemandeStatusHistoryWhereUniqueInput
  ): Promise<DemandeStatusHistory | null> {
    try {
      return await this.service.deleteDemandeStatusHistory({
        where: params,
        select: {
          createdAt: true,

          demande: {
            select: {
              id: true,
            },
          },

          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
