/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { DemandeDetteDetail } from "./DemandeDetteDetail";
import { DemandeDetteDetailCountArgs } from "./DemandeDetteDetailCountArgs";
import { DemandeDetteDetailFindManyArgs } from "./DemandeDetteDetailFindManyArgs";
import { DemandeDetteDetailFindUniqueArgs } from "./DemandeDetteDetailFindUniqueArgs";
import { CreateDemandeDetteDetailArgs } from "./CreateDemandeDetteDetailArgs";
import { UpdateDemandeDetteDetailArgs } from "./UpdateDemandeDetteDetailArgs";
import { DeleteDemandeDetteDetailArgs } from "./DeleteDemandeDetteDetailArgs";
import { Demande } from "../../demande/base/Demande";
import { DemandeDetteDetailService } from "../demandeDetteDetail.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DemandeDetteDetail)
export class DemandeDetteDetailResolverBase {
  constructor(
    protected readonly service: DemandeDetteDetailService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DemandeDetteDetail",
    action: "read",
    possession: "any",
  })
  async _demandeDetteDetailsMeta(
    @graphql.Args() args: DemandeDetteDetailCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DemandeDetteDetail])
  @nestAccessControl.UseRoles({
    resource: "DemandeDetteDetail",
    action: "read",
    possession: "any",
  })
  async demandeDetteDetails(
    @graphql.Args() args: DemandeDetteDetailFindManyArgs
  ): Promise<DemandeDetteDetail[]> {
    return this.service.demandeDetteDetails(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DemandeDetteDetail, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DemandeDetteDetail",
    action: "read",
    possession: "own",
  })
  async demandeDetteDetail(
    @graphql.Args() args: DemandeDetteDetailFindUniqueArgs
  ): Promise<DemandeDetteDetail | null> {
    const result = await this.service.demandeDetteDetail(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DemandeDetteDetail)
  @nestAccessControl.UseRoles({
    resource: "DemandeDetteDetail",
    action: "create",
    possession: "any",
  })
  async createDemandeDetteDetail(
    @graphql.Args() args: CreateDemandeDetteDetailArgs
  ): Promise<DemandeDetteDetail> {
    return await this.service.createDemandeDetteDetail({
      ...args,
      data: {
        ...args.data,

        demande: {
          connect: args.data.demande,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DemandeDetteDetail)
  @nestAccessControl.UseRoles({
    resource: "DemandeDetteDetail",
    action: "update",
    possession: "any",
  })
  async updateDemandeDetteDetail(
    @graphql.Args() args: UpdateDemandeDetteDetailArgs
  ): Promise<DemandeDetteDetail | null> {
    try {
      return await this.service.updateDemandeDetteDetail({
        ...args,
        data: {
          ...args.data,

          demande: {
            connect: args.data.demande,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DemandeDetteDetail)
  @nestAccessControl.UseRoles({
    resource: "DemandeDetteDetail",
    action: "delete",
    possession: "any",
  })
  async deleteDemandeDetteDetail(
    @graphql.Args() args: DeleteDemandeDetteDetailArgs
  ): Promise<DemandeDetteDetail | null> {
    try {
      return await this.service.deleteDemandeDetteDetail(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Demande, {
    nullable: true,
    name: "demande",
  })
  @nestAccessControl.UseRoles({
    resource: "Demande",
    action: "read",
    possession: "any",
  })
  async getDemande(
    @graphql.Parent() parent: DemandeDetteDetail
  ): Promise<Demande | null> {
    const result = await this.service.getDemande(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
