/*
------------------------------------------------------------------------------
This code was generated by Amplication.

Changes to this file will be lost if the code is regenerated.

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DemandeDetteDetailService } from "../demandeDetteDetail.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DemandeDetteDetailCreateInput } from "./DemandeDetteDetailCreateInput";
import { DemandeDetteDetail } from "./DemandeDetteDetail";
import { DemandeDetteDetailFindManyArgs } from "./DemandeDetteDetailFindManyArgs";
import { DemandeDetteDetailWhereUniqueInput } from "./DemandeDetteDetailWhereUniqueInput";
import { DemandeDetteDetailUpdateInput } from "./DemandeDetteDetailUpdateInput";

const SELECT = {
  createdAt: true,
  demande: {
    select: {
      id: true,
    },
  },
  id: true,
  nom: true,
  montant: true,
  updatedAt: true,
} as const;

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DemandeDetteDetailControllerBase {
  constructor(
    protected readonly service: DemandeDetteDetailService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DemandeDetteDetail })
  @nestAccessControl.UseRoles({
    resource: "DemandeDetteDetail",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDemandeDetteDetail(
    @common.Body() data: DemandeDetteDetailCreateInput
  ): Promise<DemandeDetteDetail> {
    return await this.service.createDemandeDetteDetail({
      data: {
        ...data,

        demande: {
          connect: data.demande,
        },
      },
      select: SELECT,
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DemandeDetteDetail] })
  @ApiNestedQuery(DemandeDetteDetailFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DemandeDetteDetail",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async demandeDetteDetails(
    @common.Req() request: Request
  ): Promise<DemandeDetteDetail[]> {
    const args = plainToClass(DemandeDetteDetailFindManyArgs, request.query);
    return this.service.demandeDetteDetails({
      ...args,
      select: SELECT,
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DemandeDetteDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DemandeDetteDetail",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async demandeDetteDetail(
    @common.Param() params: DemandeDetteDetailWhereUniqueInput
  ): Promise<DemandeDetteDetail | null> {
    const result = await this.service.demandeDetteDetail({
      where: params,
      select: SELECT,
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DemandeDetteDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DemandeDetteDetail",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDemandeDetteDetail(
    @common.Param() params: DemandeDetteDetailWhereUniqueInput,
    @common.Body() data: DemandeDetteDetailUpdateInput
  ): Promise<DemandeDetteDetail | null> {
    try {
      return await this.service.updateDemandeDetteDetail({
        where: params,
        data: {
          ...data,

          demande: {
            connect: data.demande,
          },
        },
        select: SELECT,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DemandeDetteDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DemandeDetteDetail",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDemandeDetteDetail(
    @common.Param() params: DemandeDetteDetailWhereUniqueInput
  ): Promise<DemandeDetteDetail | null> {
    try {
      return await this.service.deleteDemandeDetteDetail({
        where: params,
        select: SELECT,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
