/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  DemandeDetteDetail as PrismaDemandeDetteDetail,
  Demande as PrismaDemande,
} from "@prisma/client";

export class DemandeDetteDetailServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DemandeDetteDetailCountArgs, "select">
  ): Promise<number> {
    return this.prisma.demandeDetteDetail.count(args);
  }

  async demandeDetteDetails(
    args: Prisma.DemandeDetteDetailFindManyArgs
  ): Promise<PrismaDemandeDetteDetail[]> {
    return this.prisma.demandeDetteDetail.findMany(args);
  }
  async demandeDetteDetail(
    args: Prisma.DemandeDetteDetailFindUniqueArgs
  ): Promise<PrismaDemandeDetteDetail | null> {
    return this.prisma.demandeDetteDetail.findUnique(args);
  }
  async createDemandeDetteDetail(
    args: Prisma.DemandeDetteDetailCreateArgs
  ): Promise<PrismaDemandeDetteDetail> {
    return this.prisma.demandeDetteDetail.create(args);
  }
  async updateDemandeDetteDetail(
    args: Prisma.DemandeDetteDetailUpdateArgs
  ): Promise<PrismaDemandeDetteDetail> {
    return this.prisma.demandeDetteDetail.update(args);
  }
  async deleteDemandeDetteDetail(
    args: Prisma.DemandeDetteDetailDeleteArgs
  ): Promise<PrismaDemandeDetteDetail> {
    return this.prisma.demandeDetteDetail.delete(args);
  }

  async getDemande(parentId: number): Promise<PrismaDemande | null> {
    return this.prisma.demandeDetteDetail
      .findUnique({
        where: { id: parentId },
      })
      .demande();
  }
}
