/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsDate,
  ValidateNested,
  IsOptional,
  IsInt,
  IsString,
  MaxLength,
  IsBoolean,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { Document } from "../../document/base/Document";
import { EnumTypeDocumentRattachement } from "./EnumTypeDocumentRattachement";

@ObjectType()
class TypeDocument {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [Document],
  })
  @ValidateNested()
  @Type(() => Document)
  @IsOptional()
  documents?: Array<Document>;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  id!: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  internalCode!: string | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isInternal!: boolean;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  label!: string;

  @ApiProperty({
    required: true,
    enum: EnumTypeDocumentRattachement,
  })
  @IsEnum(EnumTypeDocumentRattachement)
  @Field(() => EnumTypeDocumentRattachement, {
    nullable: true,
  })
  rattachement?: "Contact" | "Demande" | "Suivi" | "Aide";

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  // Champs ajoutes a la main (hors generation Amplication) pour la page
  // publique de depot de justificatifs.
  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  publicUploadEnabled!: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;
}

export { TypeDocument as TypeDocument };
