/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DemandeService } from "../demande.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DemandeCreateInput } from "./DemandeCreateInput";
import { Demande } from "./Demande";
import { DemandeFindManyArgs } from "./DemandeFindManyArgs";
import { DemandeWhereUniqueInput } from "./DemandeWhereUniqueInput";
import { DemandeUpdateInput } from "./DemandeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DemandeControllerBase {
  constructor(
    protected readonly service: DemandeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Demande })
  @nestAccessControl.UseRoles({
    resource: "Demande",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDemande(
    @common.Body() data: DemandeCreateInput
  ): Promise<Demande> {
    return await this.service.createDemande({
      data: {
        ...data,

        contact: {
          connect: data.contact,
        },

        visites: data.visites
          ? {
              connect: data.visites,
            }
          : undefined,
      },
      select: {
        agesEnfants: true,
        apl: true,
        autresAides: true,
        autresCharges: true,

        contact: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dettes: true,
        facturesEnergie: true,
        id: true,
        loyer: true,
        natureDettes: true,
        nombreEnfants: true,
        remarques: true,
        revenus: true,
        revenusConjoint: true,
        situationFamiliale: true,
        situationProConjoint: true,
        situationProfessionnelle: true,
        status: true,
        updatedAt: true,

        visites: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Demande] })
  @ApiNestedQuery(DemandeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Demande",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async demandes(@common.Req() request: Request): Promise<Demande[]> {
    const args = plainToClass(DemandeFindManyArgs, request.query);
    return this.service.demandes({
      ...args,
      select: {
        agesEnfants: true,
        apl: true,
        autresAides: true,
        autresCharges: true,

        contact: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dettes: true,
        facturesEnergie: true,
        id: true,
        loyer: true,
        natureDettes: true,
        nombreEnfants: true,
        remarques: true,
        revenus: true,
        revenusConjoint: true,
        situationFamiliale: true,
        situationProConjoint: true,
        situationProfessionnelle: true,
        status: true,
        updatedAt: true,

        visites: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Demande })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Demande",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async demande(
    @common.Param() params: DemandeWhereUniqueInput
  ): Promise<Demande | null> {
    const result = await this.service.demande({
      where: params,
      select: {
        agesEnfants: true,
        apl: true,
        autresAides: true,
        autresCharges: true,

        contact: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dettes: true,
        facturesEnergie: true,
        id: true,
        loyer: true,
        natureDettes: true,
        nombreEnfants: true,
        remarques: true,
        revenus: true,
        revenusConjoint: true,
        situationFamiliale: true,
        situationProConjoint: true,
        situationProfessionnelle: true,
        status: true,
        updatedAt: true,

        visites: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Demande })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Demande",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDemande(
    @common.Param() params: DemandeWhereUniqueInput,
    @common.Body() data: DemandeUpdateInput
  ): Promise<Demande | null> {
    try {
      return await this.service.updateDemande({
        where: params,
        data: {
          ...data,

          contact: {
            connect: data.contact,
          },

          visites: data.visites
            ? {
                connect: data.visites,
              }
            : undefined,
        },
        select: {
          agesEnfants: true,
          apl: true,
          autresAides: true,
          autresCharges: true,

          contact: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          dettes: true,
          facturesEnergie: true,
          id: true,
          loyer: true,
          natureDettes: true,
          nombreEnfants: true,
          remarques: true,
          revenus: true,
          revenusConjoint: true,
          situationFamiliale: true,
          situationProConjoint: true,
          situationProfessionnelle: true,
          status: true,
          updatedAt: true,

          visites: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Demande })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Demande",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDemande(
    @common.Param() params: DemandeWhereUniqueInput
  ): Promise<Demande | null> {
    try {
      return await this.service.deleteDemande({
        where: params,
        select: {
          agesEnfants: true,
          apl: true,
          autresAides: true,
          autresCharges: true,

          contact: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          dettes: true,
          facturesEnergie: true,
          id: true,
          loyer: true,
          natureDettes: true,
          nombreEnfants: true,
          remarques: true,
          revenus: true,
          revenusConjoint: true,
          situationFamiliale: true,
          situationProConjoint: true,
          situationProfessionnelle: true,
          status: true,
          updatedAt: true,

          visites: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
