/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VersementService } from "../versement.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VersementCreateInput } from "./VersementCreateInput";
import { Versement } from "./Versement";
import { VersementFindManyArgs } from "./VersementFindManyArgs";
import { VersementWhereUniqueInput } from "./VersementWhereUniqueInput";
import { VersementUpdateInput } from "./VersementUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VersementControllerBase {
  constructor(
    protected readonly service: VersementService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Versement })
  @nestAccessControl.UseRoles({
    resource: "Versement",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVersement(
    @common.Body() data: VersementCreateInput
  ): Promise<Versement> {
    return await this.service.createVersement({
      data: {
        ...data,

        aide: {
          connect: data.aide,
        },

        document: data.document
          ? {
              connect: data.document,
            }
          : undefined,
      },
      select: {
        aide: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dataVersement: true,

        document: {
          select: {
            id: true,
          },
        },

        id: true,
        montant: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Versement] })
  @ApiNestedQuery(VersementFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Versement",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async versements(@common.Req() request: Request): Promise<Versement[]> {
    const args = plainToClass(VersementFindManyArgs, request.query);
    return this.service.versements({
      ...args,
      select: {
        aide: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dataVersement: true,

        document: {
          select: {
            id: true,
          },
        },

        id: true,
        montant: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Versement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Versement",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async versement(
    @common.Param() params: VersementWhereUniqueInput
  ): Promise<Versement | null> {
    const result = await this.service.versement({
      where: params,
      select: {
        aide: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dataVersement: true,

        document: {
          select: {
            id: true,
          },
        },

        id: true,
        montant: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Versement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Versement",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVersement(
    @common.Param() params: VersementWhereUniqueInput,
    @common.Body() data: VersementUpdateInput
  ): Promise<Versement | null> {
    try {
      return await this.service.updateVersement({
        where: params,
        data: {
          ...data,

          aide: {
            connect: data.aide,
          },

          document: data.document
            ? {
                connect: data.document,
              }
            : undefined,
        },
        select: {
          aide: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          dataVersement: true,

          document: {
            select: {
              id: true,
            },
          },

          id: true,
          montant: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Versement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Versement",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVersement(
    @common.Param() params: VersementWhereUniqueInput
  ): Promise<Versement | null> {
    try {
      return await this.service.deleteVersement({
        where: params,
        select: {
          aide: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          dataVersement: true,

          document: {
            select: {
              id: true,
            },
          },

          id: true,
          montant: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
