/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Demande } from "./Demande";
import { DemandeCountArgs } from "./DemandeCountArgs";
import { DemandeFindManyArgs } from "./DemandeFindManyArgs";
import { DemandeFindUniqueArgs } from "./DemandeFindUniqueArgs";
import { DeleteDemandeArgs } from "./DeleteDemandeArgs";
import { DemandeService } from "../demande.service";
@graphql.Resolver(() => Demande)
export class DemandeResolverBase {
  constructor(protected readonly service: DemandeService) {}

  async _demandesMeta(
    @graphql.Args() args: DemandeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Demande])
  async demandes(
    @graphql.Args() args: DemandeFindManyArgs
  ): Promise<Demande[]> {
    return this.service.demandes(args);
  }

  @graphql.Query(() => Demande, { nullable: true })
  async demande(
    @graphql.Args() args: DemandeFindUniqueArgs
  ): Promise<Demande | null> {
    const result = await this.service.demande(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Demande)
  async deleteDemande(
    @graphql.Args() args: DeleteDemandeArgs
  ): Promise<Demande | null> {
    try {
      return await this.service.deleteDemande(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
